window.athleteProfiles = {
  'Henrik 🤡': {
    gueId: null,
    stravaId: 3657050,
    fullName: '🤪 Henrik 🤡',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/3657050/1567431/1/medium.jpg',
    city: 'Oslo',
    country: 'Norge',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Adam M.': {
    gueId: null,
    stravaId: 32478034,
    fullName: 'Adam Mikos',
    stravaImg: 'https://graph.facebook.com/2039456749406875/picture?height=256&width=256',
    city: 'Budapest',
    country: 'Hungary',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Adelaide A.': {
    gueId: null,
    stravaId: 104810335,
    fullName: 'Adelaide Antunes',
    stravaImg: 'https://graph.facebook.com/10216966765360228/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Adrian B.': {
    gueId: null,
    stravaId: 15402818,
    fullName: 'Adrian Bill',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocLLwyDIVPUXRqeCL1mWgYEhSSJLzTJgu9DU9xP7K1zzaXfHSxIYYg=s96-c',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Ahmed R.': {
    gueId: null,
    stravaId: 96566133,
    fullName: 'Ahmed Radwan',
    stravaImg: 'https://lh3.googleusercontent.com/a-/AOh14GgilVOmNa8REVNRBDqZ0dXAbQi0ik0pZQf9UrSu=s96-c',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Akon D.': {
    gueId: null,
    stravaId: 118418715,
    fullName: 'Akon Dxb',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/118418715/30351905/2/medium.jpg',
    city: 'Dubai',
    country: 'United Arab Emirates',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Alba R.': {
    gueId: null,
    stravaId: 177992751,
    fullName: 'Alba Rodriguez Vallejo',
    stravaImg: '',
    city: 'Dubai',
    country: 'United Arab Emirates',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Alberto⚡ C.': {
    gueId: null,
    stravaId: 64766763,
    fullName: 'Alberto⚡ Chipolas⚡',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/64766763/16231743/9/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Alejandro E.': {
    gueId: null,
    stravaId: 178880146,
    fullName: 'Alejandro Escobar',
    stravaImg: '',
    city: 'Cape Girardeau, Missouri',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Alex A.': {
    gueId: null,
    stravaId: 2572340,
    fullName: 'Alex Angenent',
    stravaImg: '',
    city: 'Vlaardingen, Zuid-Holland',
    country: 'Netherlands',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Ali Ş.': {
    gueId: null,
    stravaId: 135752437,
    fullName: 'Ali Şener',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocI0tpJENcw3ShLr9fOYSVFZzuYxyB2UpkEcEqMF0AEPV1c7YK4=s96-c',
    city: 'Antalya',
    country: 'Türkiye',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Alicja U.': {
    gueId: null,
    stravaId: 73746542,
    fullName: 'Alicja Ulejczyk',
    stravaImg: 'https://graph.facebook.com/1581190835408794/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Alvaro J.': {
    gueId: null,
    stravaId: 58131950,
    fullName: 'Alvaro Jimenez',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/58131950/28025542/1/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Andreas B.': {
    gueId: null,
    stravaId: 145947660,
    fullName: 'Andreas Bork',
    stravaImg: '',
    city: 'Zürich',
    country: 'Switzerland',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Andrew B.': {
    gueId: null,
    stravaId: 39360282,
    fullName: 'Andrew Bowles',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/39360282/38440702/1/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Andrew H.': {
    gueId: null,
    stravaId: 15956769,
    fullName: 'Andrew Hill',
    stravaImg: 'https://graph.facebook.com/10101246789301108/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Anna L.': {
    gueId: null,
    stravaId: 55382018,
    fullName: 'Anna Lamberts',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/55382018/22691839/1/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Antonio N.': {
    gueId: null,
    stravaId: 179518693,
    fullName: 'Antonio Neves',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocKrUZU-S3EkCuuvWEU5yGQxggU2EH98NKPaeEWJgiXbrYjSloQm=s96-c',
    city: 'Tampa, Florida',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Areej B.': {
    gueId: null,
    stravaId: 174631359,
    fullName: 'Areej B',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocKMhvZCxXpRhjnFSdXnV1PZcIn2Z8mfhqXpyRfRfuATyt1jp1AC=s96-c',
    city: 'Riyadh',
    country: 'Saudi Arabia',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Asutay A.': {
    gueId: null,
    stravaId: 140752679,
    fullName: 'Asutay Akbayir',
    stravaImg: '',
    city: 'Ankara',
    country: 'Türkiye',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Becks H.': {
    gueId: null,
    stravaId: 55152689,
    fullName: 'Becks Henze',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/55152689/18253066/2/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Belen A.': {
    gueId: null,
    stravaId: 31338020,
    fullName: 'Belen Andres',
    stravaImg: 'https://graph.facebook.com/10100777587088883/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Benjamin S.': {
    gueId: null,
    stravaId: 176017859,
    fullName: 'Benjamin Schreiner',
    stravaImg: '',
    city: 'Schoden, Rhineland-Palatinate',
    country: 'Germany',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Birgul E.': {
    gueId: null,
    stravaId: 179257004,
    fullName: 'Birgül Eker',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/179257004/39263233/1/medium.jpg',
    city: 'Denizli',
    country: 'Türkiye',
    clubs: ['GUE TR'],
    isAdmin: false,
    isActive: true
  },
  'Brad K.': {
    gueId: null,
    stravaId: 26848941,
    fullName: 'Brad Kiehl',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/26848941/37548451/2/medium.jpg',
    city: 'Two Rivers, Wisconsin',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Britta H.': {
    gueId: null,
    stravaId: 52613101,
    fullName: 'Britta Hennes',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/52613101/13953529/2/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Bruno Gucci B.': {
    gueId: null,
    stravaId: 44089182,
    fullName: 'Bruno Gucci Bratan',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/44089182/14757251/1/medium.jpg',
    city: 'Berlin',
    country: 'Germany',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Cai C.': {
    gueId: null,
    stravaId: 29008913,
    fullName: 'Cai Cai',
    stravaImg: '',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Chansong [.': {
    gueId: null,
    stravaId: 673466,
    fullName: 'Chansong [FreeSkier]Moon',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/673466/145029/1/medium.jpg',
    city: 'Seoul',
    country: 'South Korea',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Chloe T.': {
    gueId: null,
    stravaId: 131997165,
    fullName: 'Chloe Touze',
    stravaImg: 'https://graph.facebook.com/2709223679128749/picture?height=256&width=256',
    city: 'Boise, Idaho',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Chris H.': {
    gueId: null,
    stravaId: 11785417,
    fullName: 'Chris Hart',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/11785417/3580152/10/medium.jpg',
    city: 'Washington, District of Columbia',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Christiaan B.': {
    gueId: null,
    stravaId: 152255777,
    fullName: 'Christiaan Bosma',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/152255777/34119261/2/medium.jpg',
    city: 'Hoogeveen , Drenthe',
    country: 'Netherlands',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'CHRISTIAN O.': {
    gueId: null,
    stravaId: 60874670,
    fullName: 'Christian Olsen',
    stravaImg: '',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Christian S.': {
    gueId: null,
    stravaId: 92306120,
    fullName: 'Christian Schweiger',
    stravaImg: '',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Christine G.': {
    gueId: null,
    stravaId: 85120907,
    fullName: 'Christine Grosart',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/85120907/20409444/2/medium.jpg',
    city: '',
    country: 'England, United Kingdom',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Cinzia R.': {
    gueId: null,
    stravaId: 179585842,
    fullName: 'Cinzia Richichi',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocKlWPS8EnGTmPMYVhH6GyTQNxnzZ2Kwg4QPefGtRZ0fZhjdh00f=s96-c',
    city: 'Zürich',
    country: 'Switzerland',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Claude L.': {
    gueId: null,
    stravaId: 10995,
    fullName: 'Claude Luu',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/10995/12356341/4/medium.jpg',
    city: 'San Jose, CA',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Claudio P.': {
    gueId: null,
    stravaId: 179560449,
    fullName: 'Claudio Provenzani',
    stravaImg: '',
    city: 'Roma, Lazio',
    country: 'Italy',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Clayton T.': {
    gueId: null,
    stravaId: 148697911,
    fullName: 'Clayton Taylor',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/148697911/35131291/1/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Cody M.': {
    gueId: null,
    stravaId: 179487763,
    fullName: 'Cody McCord',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocL5QsTb9_BhZAGtdZiQVuTGPmAO1vDMw58ZYKRjOQjnFzDTKyvc=s96-c',
    city: ' Irvine, California',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Coline M.': {
    gueId: null,
    stravaId: 179417453,
    fullName: 'Coline Martineau',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocJoVYNe1YT3e-39iMANlqqacZAqKybhWObqFxgykFnThGaSHTE=s96-c',
    city: 'Rezé, Pays de la Loire',
    country: 'France',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Connor K.': {
    gueId: null,
    stravaId: 179554125,
    fullName: 'Connor Kwan',
    stravaImg: '',
    city: 'Hong Kong Island, Hong Kong',
    country: 'China',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Cornelia E.': {
    gueId: null,
    stravaId: 95679835,
    fullName: 'Cornelia Elbert',
    stravaImg: 'https://graph.facebook.com/10224520299733850/picture?height=256&width=256',
    city: 'Bonn',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Craig J.': {
    gueId: null,
    stravaId: 1297106,
    fullName: 'Craig James',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/1297106/1649488/2/medium.jpg',
    city: 'Perth, Western Australia',
    country: 'Australia',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Csaba S.': {
    gueId: null,
    stravaId: 69345764,
    fullName: 'Csaba Szilágyi',
    stravaImg: '',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Cyrill W.': {
    gueId: null,
    stravaId: 105740454,
    fullName: 'Cyrill Wiget',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocLk_bsHiknOEY5MhYr1j8u_IWAQQA_Vaxars93zan8KJTkQf2Uq=s96-c',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Dan W.': {
    gueId: null,
    stravaId: 33932571,
    fullName: 'Dan Webster',
    stravaImg: 'https://graph.facebook.com/10156291375090733/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Daniel D.': {
    gueId: null,
    stravaId: 98620997,
    fullName: 'Daniel Dudek',
    stravaImg: '',
    city: 'Frankfurt am Main, Hessen',
    country: 'Germany',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Daniel H.': {
    gueId: null,
    stravaId: 179594742,
    fullName: 'Daniel Hasak-Lieb',
    stravaImg: '',
    city: 'Würzburg, Bayern',
    country: 'Germany',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Daniel O.': {
    gueId: null,
    stravaId: 154104604,
    fullName: 'Daniel Ortega',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/154104604/34541445/1/medium.jpg',
    city: 'Murrieta, California',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Daniel S.': {
    gueId: null,
    stravaId: 4710920,
    fullName: 'Daniel Stevens',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/4710920/9331485/1/medium.jpg',
    city: 'PL68TG',
    country: 'England, United Kingdom',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Danny T.': {
    gueId: null,
    stravaId: 143921216,
    fullName: 'Danny Tong',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/143921216/32557800/1/medium.jpg',
    city: 'Seattle, Washington',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Darek L.': {
    gueId: null,
    stravaId: 74812890,
    fullName: 'Darek Lutkiewicz',
    stravaImg: '',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Dario T.': {
    gueId: null,
    stravaId: 10191119,
    fullName: 'Dario Trombetta 🏴‍☠️',
    stravaImg: 'https://graph.facebook.com/10155781521695057/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Dave S.': {
    gueId: null,
    stravaId: 54249012,
    fullName: 'Dave Smith',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocJKV0VXJxwpR2XSuz2UGPT-3IKZ0Tx-oeX46LQCQ9jWFvbfXcdn=s96-c',
    city: 'Lancaster',
    country: 'England, United Kingdom',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'David B.': {
    gueId: null,
    stravaId: 76494044,
    fullName: 'David Bravo',
    stravaImg: '',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'David C.': {
    gueId: null,
    stravaId: 179348045,
    fullName: 'David Cowan',
    stravaImg: '',
    city: 'Maylands, South Australia',
    country: 'Australia',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Deana F.': {
    gueId: null,
    stravaId: 179605632,
    fullName: 'Deana Fraser',
    stravaImg: '',
    city: 'Kent, Washington',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Dimitris P.': {
    gueId: null,
    stravaId: 19268182,
    fullName: 'Dimitris Papakonstantis🏴‍☠️',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/19268182/24476732/1/medium.jpg',
    city: 'Aberdeen',
    country: 'Scotland, United Kingdom',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Diouri Y.': {
    gueId: null,
    stravaId: 24071766,
    fullName: 'Diouri Youssef',
    stravaImg: 'https://graph.facebook.com/1434127603345848/picture?height=256&width=256',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'DM P.': {
    gueId: null,
    stravaId: 22438392,
    fullName: 'DM P',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/22438392/15970427/1/medium.jpg',
    city: 'Vilnius, Vilniaus apskritis',
    country: 'Lithuania',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Dorota C.': {
    gueId: null,
    stravaId: 114274230,
    fullName: 'Dorota Czerny',
    stravaImg: '',
    city: 'Dorgali, Nuoro',
    country: 'Italy',
    clubs: [],
    isAdmin: true,
    isActive: true
  },
  'Doug J.': {
    gueId: null,
    stravaId: 117536,
    fullName: 'Doug Junkins',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/117536/17488/5/medium.jpg',
    city: 'Seattle, Washington',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Doug R.': {
    gueId: null,
    stravaId: 19358370,
    fullName: 'Doug Ray',
    stravaImg: '',
    city: 'Gainesville, Florida',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Eduardo F.': {
    gueId: null,
    stravaId: 65792352,
    fullName: 'Eduardo Ferrer',
    stravaImg: 'https://graph.facebook.com/10159165086448210/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Elma T.': {
    gueId: null,
    stravaId: 25377421,
    fullName: 'Elma Tarr',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/25377421/10421638/2/medium.jpg',
    city: 'Giant South Coast',
    country: 'South Africa',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Emilie B.': {
    gueId: null,
    stravaId: 75584005,
    fullName: 'Emilie Bouthillette',
    stravaImg: 'https://graph.facebook.com/10157535998036389/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Emir M.': {
    gueId: null,
    stravaId: 105011014,
    fullName: 'Emir Memic',
    stravaImg: 'https://graph.facebook.com/10217039830508061/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Emoke W.': {
    gueId: null,
    stravaId: 179518995,
    fullName: 'Emoke Wagner',
    stravaImg: '',
    city: 'Playa del Carmen, Quintana Roo',
    country: 'Mexico',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'EngBoon T.': {
    gueId: null,
    stravaId: 93070399,
    fullName: 'EngBoon Tan',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/93070399/22192938/1/medium.jpg',
    city: '',
    country: 'Singapore',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'EngHan N.': {
    gueId: null,
    stravaId: 15913515,
    fullName: 'EngHan Ng',
    stravaImg: 'https://graph.facebook.com/10100743657670866/picture?height=256&width=256',
    city: '',
    country: 'Singapore',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Eric F.': {
    gueId: null,
    stravaId: 47682299,
    fullName: 'Eric Fine',
    stravaImg: 'https://graph.facebook.com/10159543475852978/picture?height=256&width=256',
    city: 'Massachusetts',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Eric M.': {
    gueId: null,
    stravaId: 64704764,
    fullName: 'Eric Marchwinski',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocJbC0zPQeHr6_UuzYM1A2997UzOtoDs6IjF1ISk9oCPNKA=s96-c',
    city: 'New Rochelle, New York',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Erik H.': {
    gueId: null,
    stravaId: 66833482,
    fullName: 'Erik Hoffmann',
    stravaImg: '',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Evelyn U.': {
    gueId: null,
    stravaId: 175062794,
    fullName: 'Evelyn Unti',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocKubXO5oPsnrS2Ajg_3Q42P9ecz4PnuLLCEvIOzG94tzKnmcg=s96-c',
    city: 'Florida',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Fabian G.': {
    gueId: null,
    stravaId: 22249770,
    fullName: 'Fabian Gast',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/22249770/13115919/1/medium.jpg',
    city: 'München, Bavaria',
    country: 'Germany',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Fabrizio T.': {
    gueId: null,
    stravaId: 71218612,
    fullName: 'Fabrizio Tosoni',
    stravaImg: 'https://graph.facebook.com/10158683856751101/picture?height=256&width=256',
    city: 'Bunde, Lower Saxony',
    country: 'Germany',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Fany B.': {
    gueId: null,
    stravaId: 66185972,
    fullName: 'Fany Barcham',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/66185972/17979706/4/medium.jpg',
    city: 'Abu Dhabi',
    country: 'United Arab Emirates',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Ferry S.': {
    gueId: null,
    stravaId: 56002531,
    fullName: 'Ferry Schram',
    stravaImg: 'https://lh3.googleusercontent.com/a-/AOh14Ggezk8iryxeGKEjBEKiSprLHwFOVMggkVuytgi7',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Floris V.': {
    gueId: null,
    stravaId: 81232028,
    fullName: 'Floris Van der Est',
    stravaImg: '',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Francisco Javier L.': {
    gueId: null,
    stravaId: 179515040,
    fullName: 'Francisco Javier Lopez Ruiz',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocLiIOEFgHEHssIsm8onjd9V-LvS9qTR05qe-pWCAn18e92lSMdq=s96-c',
    city: 'Playa del Carmen, Quintana Roo',
    country: 'Mexico',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Frankee Deann H.': {
    gueId: null,
    stravaId: 174635816,
    fullName: 'Frankee Deann Hoss',
    stravaImg: 'https://graph.facebook.com/970951456288806/picture?height=256&width=256',
    city: 'Gainesville , Florida',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Fred S.': {
    gueId: null,
    stravaId: 179565425,
    fullName: 'Fred Scubagedoven',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/179565425/39264702/1/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Gabi S.': {
    gueId: null,
    stravaId: 120698386,
    fullName: 'Gabi Sleeman',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/120698386/39029972/1/medium.jpg',
    city: 'Grand Rapids, Michigan',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Gareth L.': {
    gueId: null,
    stravaId: 20077564,
    fullName: 'Gareth Lock',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/20077564/9534445/4/medium.jpg',
    city: 'Malmesbury',
    country: 'England, United Kingdom',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Gaute S.': {
    gueId: null,
    stravaId: 36439080,
    fullName: 'Gaute Seljestad',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocJBIy7VJyliYSagme-wzSiVx4AbYIOIhoirz4GaXbG5xm48KHpqCQ=s96-c',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Geir A.': {
    gueId: null,
    stravaId: 23504509,
    fullName: 'Geir Alstad',
    stravaImg: 'https://graph.facebook.com/10152346551411043/picture?height=256&width=256',
    city: 'Oslo',
    country: 'Norway',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'George L.': {
    gueId: null,
    stravaId: 58167619,
    fullName: 'George Linnane',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/58167619/14983658/3/medium.jpg',
    city: 'Bristol',
    country: 'United Kingdom',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Gözde A.': {
    gueId: null,
    stravaId: 140743703,
    fullName: 'Gözde Akbayir',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocJ32t_SHZxex2r8xIMwhblr0cmD5jJsm2r-UaPzdECG1U1LiYqK=s96-c',
    city: 'Ankara',
    country: 'Türkiye',
    clubs: [],
    isAdmin: true,
    isActive: true
  },
  'Graham W.': {
    gueId: null,
    stravaId: 7792203,
    fullName: 'Graham Wheeler',
    stravaImg: '',
    city: 'Bray, Wicklow',
    country: 'Ireland',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Greg B.': {
    gueId: null,
    stravaId: 179599775,
    fullName: 'Greg Barrick',
    stravaImg: '',
    city: 'North Richland Hills, Texas',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Hayley S.': {
    gueId: null,
    stravaId: 179551853,
    fullName: 'Hayley Seat',
    stravaImg: '',
    city: 'Upland, California',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Heiko S.': {
    gueId: null,
    stravaId: 179557109,
    fullName: 'Heiko Scheepers',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocKAsOwxGpSyiN8FGDGYEw1_vua2gMPDDaRwasTa0qPxmuLmkoFc=s96-c',
    city: 'Mönchengladbach, North Rhine-Westphalia',
    country: 'Germany',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Hongyi L.': {
    gueId: null,
    stravaId: 179575381,
    fullName: 'Hongyi Lyu',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocLlpQa_fJ9BnHVBPqgGNqG9oM14cq7FlF6OMPLjlRD3B77wxA=s96-c',
    city: 'Belmore, New South Wales',
    country: 'Australia',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Ingrid Ø.': {
    gueId: null,
    stravaId: 89792633,
    fullName: 'Ingrid Ølberg',
    stravaImg: 'https://graph.facebook.com/10157753708656467/picture?height=256&width=256',
    city: 'Oslo',
    country: 'Norway',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'isidro L.': {
    gueId: null,
    stravaId: 50504665,
    fullName: 'isidro L.G. Rutas XTREME',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/50504665/13788213/3/medium.jpg',
    city: 'Murcia',
    country: 'Spain',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'István W.': {
    gueId: null,
    stravaId: 65886261,
    fullName: 'István Wengrin',
    stravaImg: 'https://graph.facebook.com/4054553487938859/picture?height=256&width=256',
    city: 'Budapest',
    country: 'Hungary',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Ivan G.': {
    gueId: null,
    stravaId: 63789966,
    fullName: 'Ivan Granado',
    stravaImg: 'https://graph.facebook.com/10218317655149931/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Jack O.': {
    gueId: null,
    stravaId: 31795229,
    fullName: 'Jack Over',
    stravaImg: 'https://graph.facebook.com/10212320900081514/picture?height=256&width=256',
    city: 'Vinkeveen, Utrecht',
    country: 'Netherlands',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'James D.': {
    gueId: null,
    stravaId: 11015563,
    fullName: 'James Draker',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/11015563/25935489/1/medium.jpg',
    city: 'Fort White, Florida',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'James W.': {
    gueId: null,
    stravaId: 5807021,
    fullName: 'James Wookey',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/5807021/1882231/1/medium.jpg',
    city: 'London, UK',
    country: 'Australia',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Jan Henry S. F.': {
    gueId: null,
    stravaId: 103065208,
    fullName: 'Jan Henry S. Fosse',
    stravaImg: '',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Jenn T.': {
    gueId: null,
    stravaId: 24624038,
    fullName: 'Jenn Thomson',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/24624038/7088451/4/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Jennifer D.': {
    gueId: null,
    stravaId: 179359418,
    fullName: 'Jennifer Dillaman',
    stravaImg: '',
    city: 'Jacksonville, Florida',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Jesper L.': {
    gueId: null,
    stravaId: 174638958,
    fullName: 'Jesper Larsson',
    stravaImg: '',
    city: 'Västerås, Västmanlands län',
    country: 'Sweden',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Jessy T.': {
    gueId: null,
    stravaId: 179549464,
    fullName: 'Jessy Thompson',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocI1O_LhSJHnXNSvLOiSMQ0UfXg2iDKzB-pFeiNleU0ximHK=s96-c',
    city: 'Muskegon, Michigan',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'João L.': {
    gueId: null,
    stravaId: 11228766,
    fullName: 'João Lobo',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/11228766/3397656/1/medium.jpg',
    city: 'Lisbon',
    country: 'Portugal',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Johan M.': {
    gueId: null,
    stravaId: 178984033,
    fullName: 'Johan Maheux',
    stravaImg: '',
    city: 'Rennes, Bretagne',
    country: 'France',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Johannes S.': {
    gueId: null,
    stravaId: 154970111,
    fullName: 'Johannes Six',
    stravaImg: '',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'John K.': {
    gueId: null,
    stravaId: 74285124,
    fullName: 'John Kendall',
    stravaImg: '',
    city: 'Cambridge',
    country: 'England, United Kingdom',
    clubs: [],
    isAdmin: true,
    isActive: true
  },
  'John L.': {
    gueId: null,
    stravaId: 55205513,
    fullName: 'John Leeming',
    stravaImg: '',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Jonas P.': {
    gueId: null,
    stravaId: 136447355,
    fullName: 'Jonas Pröschel',
    stravaImg: 'https://graph.facebook.com/7840236752663968/picture?height=256&width=256',
    city: 'Triefenstein, Bayern',
    country: 'Germany',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Jose Ant. "pepetoni" ".': {
    gueId: null,
    stravaId: 7400922,
    // fullName: 'Jose Ant. "pepetoni" " El Plato" y Team Rutas Premium 🥑🥙🥘🥪 🍻🍻🔋🔋🪫🪫 Berria',
    fullName: 'Jose Ant. "pepetoni" " El Plato"...',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/7400922/2271072/11/medium.jpg',
    city: 'Tiñosa, S.Jose Del Vega, Región de Murcia',
    country: 'Spain',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Josh H.': {
    gueId: null,
    stravaId: 9914495,
    fullName: 'Josh Hoss',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/9914495/3512002/4/medium.jpg',
    city: 'Gainesville, Florida',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Jota P.': {
    gueId: null,
    stravaId: 481293,
    fullName: 'Jota ProfEdufis',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/481293/23479404/4/medium.jpg',
    city: 'Murcia',
    country: 'Spain',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Justine T.': {
    gueId: null,
    stravaId: 8858266,
    fullName: 'Justine Tawel',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/8858266/24796780/2/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Kata N.': {
    gueId: null,
    stravaId: 73815465,
    fullName: 'Kata Nagy',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/73815465/18176632/2/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Lara I.': {
    gueId: null,
    stravaId: 175954457,
    fullName: 'Lara Indra',
    stravaImg: '',
    city: 'Bern, Bern',
    country: 'Switzerland',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Larissa F.': {
    gueId: null,
    stravaId: 152779668,
    fullName: 'Larissa Fontenelle de Oliveira Dow',
    stravaImg: '',
    city: 'Kill Devil Hills, North Carolina',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Lauren W.': {
    gueId: null,
    stravaId: 175559428,
    fullName: 'Lauren Wilson',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/175559428/38581438/1/medium.jpg',
    city: 'Florida',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Leonidas K.': {
    gueId: null,
    stravaId: 176455897,
    fullName: 'Leonidas Kalantidis',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/176455897/38724516/1/medium.jpg',
    city: 'L-Imsida',
    country: 'Malta',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Liam E.': {
    gueId: null,
    stravaId: 32147207,
    fullName: 'Liam Edge',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/32147207/9597623/16/medium.jpg',
    city: 'Westbury',
    country: 'England, United Kingdom',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Luis F. A.': {
    gueId: null,
    stravaId: 177996489,
    fullName: 'Luis F. Astudillo',
    stravaImg: '',
    city: 'No, Nono',
    country: 'Spain',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Maciej L.': {
    gueId: null,
    stravaId: 71885525,
    fullName: 'Maciej Lewandowski',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/71885525/17556641/2/medium.jpg',
    city: 'Wólka Kozodawska, Masovian Voivodeship',
    country: 'Poland',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Malte M.': {
    gueId: null,
    stravaId: 96232901,
    fullName: 'Malte M.',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/96232901/22801986/1/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'MANTARAY L.': {
    gueId: null,
    stravaId: 4861742,
    fullName: 'Mantaray Lee',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/4861742/1562773/6/medium.jpg',
    city: 'Seoul',
    country: 'South Korea',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'MANTARAY L.2': {
    gueId: null,
    stravaId: 175060377,
    fullName: 'Mantaray Lee 2',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/4861742/1562773/6/medium.jpg',
    city: 'Seoul',
    country: 'South Korea',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Marcel K.': {
    gueId: null,
    stravaId: 16488809,
    fullName: 'Marcel Kersten',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/16488809/6360140/2/medium.jpg',
    city: 'Abcoude, Utrecht',
    country: 'Nederland',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'marcelin N.': {
    gueId: null,
    stravaId: 142385187,
    fullName: 'Marcelin Nebenhaus',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/142385187/32273652/2/medium.jpg',
    city: 'Playa del Carmen, Quintana Roo',
    country: 'Mexico',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Marcus R.': {
    gueId: null,
    stravaId: 23980658,
    fullName: 'Marcus Rose',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/23980658/28375128/1/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Mareike T.': {
    gueId: null,
    stravaId: 143170836,
    fullName: 'Mareike Trapp',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/143170836/32422072/1/medium.jpg',
    city: 'Hamburg',
    country: 'Germany',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Mark N.': {
    gueId: null,
    stravaId: 174658166,
    fullName: 'Mark Nicoletti',
    stravaImg: '',
    city: 'Miami Gardens, Florida',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Markus S.': {
    gueId: null,
    stravaId: 69537806,
    fullName: 'Markus Schyberger',
    stravaImg: 'https://graph.facebook.com/3224501550998784/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Martijn B.': {
    gueId: null,
    stravaId: 96861880,
    fullName: 'Martijn Blommaert',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/96861880/27884367/2/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Martin D.': {
    gueId: null,
    stravaId: 14426900,
    fullName: 'Martin Demper',
    stravaImg: 'https://graph.facebook.com/10209257046720098/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Martin K.': {
    gueId: null,
    stravaId: 20644523,
    fullName: 'Martin Kučera',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/20644523/21989749/3/medium.jpg',
    city: 'Bratislava',
    country: 'Slovakia',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Martin N.': {
    gueId: null,
    stravaId: 81072437,
    fullName: 'Martin Naalsund',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/81072437/19484819/1/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Matt S.': {
    gueId: null,
    stravaId: 11049272,
    fullName: 'Matt S',
    stravaImg: '',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'max F.': {
    gueId: null,
    stravaId: 129197343,
    fullName: 'Max Fahr',
    stravaImg: 'https://graph.facebook.com/7282504081780632/picture?height=256&width=256',
    city: 'Montélimar',
    country: 'Auvergne-Rhône-Alpes, France',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Maxime C.': {
    gueId: null,
    stravaId: 170918483,
    fullName: 'Maxime Cheminade',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/170918483/38768285/1/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Maximilian W.': {
    gueId: null,
    stravaId: 105963017,
    fullName: 'Maximilian Wels',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/105963017/25189426/1/medium.jpg',
    city: 'Mannheim',
    country: 'Baden-Württemberg',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Melissa P.': {
    gueId: null,
    stravaId: 34293028,
    fullName: 'Melissa Perkins',
    stravaImg: 'https://graph.facebook.com/10155430352080213/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Michael G.': {
    gueId: null,
    stravaId: 174625260,
    fullName: 'Michael Goodness',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/174625260/38437871/1/medium.jpg',
    city: 'Milwaukee, Wisconsin',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Michael T.': {
    gueId: null,
    stravaId: 13618710,
    fullName: 'Michael Tandy',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/13618710/5866792/7/medium.jpg',
    city: '',
    country: 'England, United Kingdom',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Michael W.': {
    gueId: null,
    stravaId: 106727330,
    fullName: 'Michael Westreicher',
    stravaImg: 'https://graph.facebook.com/2683171208494454/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Michaela S.': {
    gueId: null,
    stravaId: 103654397,
    fullName: 'Michaela Strazanova',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/103654397/25110944/13/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Michał R.': {
    gueId: null,
    stravaId: 22497909,
    fullName: 'Michał Ryśniak',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/22497909/8988438/2/medium.jpg',
    city: 'Warszawa',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Michiel K.': {
    gueId: null,
    stravaId: 14948783,
    fullName: 'Michiel Kraakman',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/14948783/4891919/4/medium.jpg',
    city: 'Malé',
    country: 'Malé',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Mikael S.': {
    gueId: null,
    stravaId: 115078425,
    fullName: 'Mikael Sjödin',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/115078425/27244425/1/medium.jpg',
    city: 'Ottawa, Ontario',
    country: 'Canada',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Natalia E.': {
    gueId: null,
    stravaId: 152040350,
    fullName: 'Natalia Egorova',
    stravaImg: '',
    city: 'Winter Garden, Florida',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Nestor S.': {
    gueId: null,
    stravaId: 178030805,
    fullName: 'Nestor Sandoval',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/178030805/39002806/1/medium.jpg',
    city: 'Hollywood, Florida',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Nevcan U.': {
    gueId: 20397,
    stravaId: 85805764,
    fullName: 'Nevcan Uludas',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/85805764/20559739/3/medium.jpg',
    city: 'Istanbul',
    country: 'Türkiye',
    clubs: ['GUE TR'],
    isAdmin: true,
    isActive: true
  },
  'Nick R.': {
    gueId: null,
    stravaId: 4815602,
    fullName: 'Nick Radov',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/4815602/15383271/1/medium.jpg',
    city: 'Los Gatos, California',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Nicole A.': {
    gueId: null,
    stravaId: 179340884,
    fullName: 'Nicole Alarid',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocI6uN0h5OEf1DqeOBYSwSQtnj_Kk9j87mBoUy851jA6me2COBIo=s96-c',
    city: 'Alachua, Florida',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Oğuz Ö.': {
    gueId: null,
    stravaId: 85824257,
    fullName: 'Oğuz Öz',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/85824257/25570948/1/medium.jpg',
    city: 'Isparta',
    country: 'Türkiye',
    clubs: ['GUE TR'],
    isAdmin: true,
    isActive: true
  },
  'Ol G.': {
    gueId: null,
    stravaId: 103267169,
    fullName: 'Ol Ga',
    stravaImg: 'https://graph.facebook.com/5927108187316251/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Olivia K.': {
    gueId: null,
    stravaId: 175065970,
    fullName: 'Olivia Kuhn',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocJt-E7dyfpTCo6bdrxYvLXt6e8gNSFVAiVV_E8aFpaB2S3wnpFV=s96-c',
    city: 'High Springs, Florida',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Olli T.': {
    gueId: null,
    stravaId: 154819058,
    fullName: 'Olli Taucht',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/154819058/34584957/1/medium.jpg',
    city: 'Schnevern, Niedersachsen',
    country: 'Germany',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Paige S.': {
    gueId: null,
    stravaId: 16582356,
    fullName: 'Paige Strudwick',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/16582356/24020885/2/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Pascal v.': {
    gueId: null,
    stravaId: 4447938,
    fullName: 'Pascal van Erp',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/4447938/26168401/5/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Paul L.': {
    gueId: null,
    stravaId: 106468601,
    fullName: 'Paul Laane',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/106468601/25571566/1/medium.jpg',
    city: 'Den Haag',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Peter Z.': {
    gueId: null,
    stravaId: 17110758,
    fullName: 'Peter Zaal',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/17110758/4809232/1/medium.jpg',
    city: 'Mijdrecht, Utrecht',
    country: 'Nederland',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Pietro C.': {
    gueId: null,
    stravaId: 30877351,
    fullName: 'Pietro Crovetto',
    stravaImg: 'https://graph.facebook.com/10157518556916110/picture?height=256&width=256',
    city: 'Copenhagen',
    country: 'Denmark',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Randy M.': {
    gueId: null,
    stravaId: 33261872,
    fullName: 'Randy Mintz',
    stravaImg: 'https://graph.facebook.com/10217464706395036/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Ricardo C.': {
    gueId: null,
    stravaId: 11555230,
    fullName: 'Ricardo Constantino',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/11555230/3503249/2/medium.jpg',
    city: 'Cabo de Palos',
    country: 'Spain / Portugal',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Rich W.': {
    gueId: null,
    stravaId: 18471179,
    fullName: 'Rich Walker',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/18471179/15157521/1/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Richard H.': {
    gueId: null,
    stravaId: 174641016,
    fullName: 'Richard Harpin',
    stravaImg: '',
    city: 'Mitcham, England',
    country: 'United Kingdom',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Richard T.': {
    gueId: null,
    stravaId: 108978139,
    fullName: 'Richard Tessell',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/108978139/25835281/1/medium.jpg',
    city: 'Chicago',
    country: 'IL',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Richie D.': {
    gueId: null,
    stravaId: 176357981,
    fullName: 'Richie Denmark',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocLNm0Y9VhlruZtbj3Cht2ca6NWZ1ZnfKC0-35-7I0wiKUeNDr_dQA=s96-c',
    city: 'Jacksonville, Florida',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Rick V.B.': {
    gueId: null,
    stravaId: 46233624,
    fullName: 'Rick van Beerendonk',
    stravaImg: 'https://graph.facebook.com/10220323591267824/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Rick V.D.': {
    gueId: null,
    stravaId: 47884306,
    fullName: 'Rick van Dijk',
    stravaImg: 'https://graph.facebook.com/10156040921781561/picture?height=256&width=256',
    city: 'Vinkeveen',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Rob W.': {
    gueId: null,
    stravaId: 143652257,
    fullName: 'Rob Wilson',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/143652257/32597891/1/medium.jpg',
    city: 'Wellington',
    country: 'New Zealand',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Ronald B.': {
    gueId: null,
    stravaId: 2011699,
    fullName: 'Ronald Bouwmeester',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/2011699/734608/4/medium.jpg',
    city: 'Trittenheim, R-P',
    country: 'Nederland',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Ryan C.': {
    gueId: null,
    stravaId: 10882546,
    fullName: 'Ryan Creswell',
    stravaImg: 'https://graph.facebook.com/10209424499236138/picture?height=256&width=256',
    city: 'Plattsburgh, NY',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Ryan K.': {
    gueId: null,
    stravaId: 75548548,
    fullName: 'Ryan Koesuma',
    stravaImg: 'https://graph.facebook.com/10160690510084968/picture?height=256&width=256',
    city: 'Jakarta',
    country: 'Indonesia',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Saska M.': {
    gueId: null,
    stravaId: 54497615,
    fullName: 'Saska Macnab',
    stravaImg: 'https://graph.facebook.com/3284477114897206/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Strava A.': {
    gueId: null,
    stravaId: 179337846,
    fullName: 'Strava Athlete',
    stravaImg: '',
    city: 'Stuart, Florida',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Stretch A.': {
    gueId: null,
    stravaId: 23303525,
    fullName: 'Stretch Altenhein',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/23303525/6675298/1/medium.jpg',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Sven N.': {
    gueId: null,
    stravaId: 174618357,
    fullName: 'Sven Nelles',
    stravaImg: '',
    city: 'Hürth, Nordrhein-Westfalen',
    country: 'Germany',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Tarek K.': {
    gueId: null,
    stravaId: 50048937,
    fullName: 'Tarek Krull',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/50048937/15693169/11/medium.jpg',
    city: 'Hattersheim, Hessen',
    country: 'Germany',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Terje G.': {
    gueId: null,
    stravaId: 171567745,
    fullName: 'Terje Gotteberg',
    stravaImg: 'https://lh3.googleusercontent.com/a/ACg8ocIkRNp1i9A0Ja_dnM9SiuNOAbdhDqYobbmx7wqR5fGg4ByiJw=s96-c',
    city: 'Sentrum, Oslo',
    country: 'Norway',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Tom F.': {
    gueId: null,
    stravaId: 174633182,
    fullName: 'Tom Figueroa',
    stravaImg: '',
    city: 'Los Angeles, California',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Toni N.': {
    gueId: null,
    stravaId: 8818297,
    fullName: 'Toni Norton',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/8818297/3027434/2/medium.jpg',
    city: 'Midsomer Norton',
    country: 'Somerset, United Kingdom',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Travis V.': {
    gueId: null,
    stravaId: 175506050,
    fullName: 'Travis Valcourt',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/175506050/38573656/1/medium.jpg',
    city: 'Brattleboro, Vermont',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Ulrika S.': {
    gueId: null,
    stravaId: 174638368,
    fullName: 'Ulrika Svedman',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/174638368/38440377/1/medium.jpg',
    city: 'Västerås, Västmanlands län',
    country: 'Sweden',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Warren L.': {
    gueId: null,
    stravaId: 60535203,
    fullName: 'Warren Lo',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/60535203/15460553/2/medium.jpg',
    city: 'Toronto, Ontario',
    country: 'Canada',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Yanshen S.': {
    gueId: null,
    stravaId: 167721938,
    fullName: 'Yanshen Su',
    stravaImg: '',
    city: 'San Francisco, California',
    country: 'United States',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Zach P.': {
    gueId: null,
    stravaId: 68599194,
    fullName: 'Zach Peletz',
    stravaImg: 'https://graph.facebook.com/10104819617265228/picture?height=256&width=256',
    city: 'New York',
    country: 'New York',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Zoe R.': {
    gueId: null,
    stravaId: 3617508,
    fullName: 'Zoe Read',
    stravaImg: 'https://graph.facebook.com/10153085196733641/picture?height=256&width=256',
    city: '',
    country: 'England, United Kingdom',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Zoltan N.': {
    gueId: null,
    stravaId: 21908800,
    fullName: 'Zoltan Nagy',
    stravaImg: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/21908800/11623730/1/medium.jpg',
    city: 'Törökbàlint',
    country: 'HU',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'zsolt S.': {
    gueId: null,
    stravaId: 28063987,
    fullName: 'Zsolt Szilagyi',
    stravaImg: 'https://graph.facebook.com/4362550800484608/picture?height=256&width=256',
    city: '',
    country: '',
    clubs: [],
    isAdmin: false,
    isActive: true
  },
  'Γιώργος Π.': {
    gueId: null,
    stravaId: 24896921,
    fullName: 'Γιώργος Πολυκράτης',
    stravaImg: 'https://graph.facebook.com/212130597987152/picture?height=256&width=256',
    city: 'Λευκωσία (Nicosia)',
    country: 'Cyprus',
    clubs: [],
    isAdmin: false,
    isActive: true
  }
};
